browse/urls.py
from django.conf.urls import url

from . import views

app_name = 'browse'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.WorkoutDetailView.as_view(), name='workoutdetail'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),    
]

fitjeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import browse.views

urlpatterns = [
    url(r'^$', browse.views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^wods/', include('browse.urls')),
]

browse/models.py
from django.db import models

# Create your models here.

crawl/models.py
from django.db import models

# Create your models here.
class Workout(models.Model):
    """Workout represents one WOD page. May contain duplicates."""
    __tablename__ = 'workouts'

    title = models.CharField(max_length=255)
    description = models.TextField()
    uom = models.CharField(max_length=255)
    link = models.URLField(max_length=255, help_text="URL to the WOD page")
    date = models.DateField()
    created_on = models.DateTimeField("Created on", auto_now_add=True)
    updated_on = models.DateTimeField("Updated on", auto_now=True)

    def __str__(self):
        return self.title

    def __repr__(self):
        return "<Workout(title='%s', description='%s')>" % (self.title, self.description)

class Benchmark(models.Model):
    """
    Benchmark represents the min, max and average Rx'd results for
    a Workout.
    """
    __tablename__ = 'benchmark'

    workout = models.ForeignKey(Workout, null=True)
    gender = models.CharField(max_length=255)
    min_age = models.IntegerField(null=True)
    avg_age = models.IntegerField(null=True)
    max_age = models.IntegerField(null=True)
    min_score = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    avg_score = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    max_score = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    total_score = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    rx = models.CharField(max_length=255)
    count = models.IntegerField(default=0)
    uom = models.CharField(max_length=255)

    def __str__(self):
        return "%s, %s %s" % (self.gender, self.avg_score, self.uom)
        
    def __repr__(self):
        return "<Benchmark('%s, %s %s')>" % (self.gender, self.avg_score, self.uom)

browse/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse

from crawl.models import Workout

# Create your views here.

class IndexView(generic.ListView):
    # queryset = Workout.objects.all() is the long form of model = Workout
    queryset = Workout.objects.all().order_by('-date')
    template_name = 'browse/index.html'
    context_object_name = 'workout_list'
    paginate_by = 8

class WorkoutDetailView(generic.DetailView):
    model = Workout
    template_name = 'browse/workoutdetail.html'

    def get_pretty_results(self, uom, benchmark_list):
        # Timed results are stored as decimals. Convert to minutes:seconds.
        if 'time' in uom and benchmark_list:
            for gender in benchmark_list:
                gender.min_score = "{}:{:02.0f}".format(int(gender.min_score), gender.min_score % 1 * 60) 
                gender.avg_score = "{}:{:02.0f}".format(int(gender.avg_score), gender.avg_score % 1 * 60)
                gender.max_score = "{}:{:02.0f}".format(int(gender.max_score), gender.max_score % 1 * 60)
        else:
            for gender in benchmark_list:
                gender.min_score = "{:.0f}".format(gender.min_score) 
                gender.avg_score = "{:.0f}".format(gender.avg_score)
                gender.max_score = "{:.0f}".format(gender.max_score)
        # Make gender readable
        gender_key = {"F":"Female","M":"Male","E":"Not Specified"}
        for gender in benchmark_list: gender.gender = gender_key[gender.gender]
        return benchmark_list

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(WorkoutDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet for benchmarks
        context['benchmark_list'] = context['workout'].benchmark_set.all()
        # Change format of results for better readability
        context['benchmark_list'] = self.get_pretty_results(context['workout'].uom, context['benchmark_list'])
        return context

class AboutView(generic.TemplateView):
    template_name = 'browse/about.html'

class ContactView(generic.TemplateView):
    template_name = 'browse/contact.html'

crawl/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse

browse/templates/browse/about.html
{% extends "./base.html" %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>About</h1>
        <p class="lead">The main website has a very active community, but the results in the comments aren't captured anywhere. Fit-j.com is a hobby so please be patient if something doesn't work quite right. Give your thoughts and feedback by leaving a note!</p>
    </div> <!-- jumbotron -->
</div>
{% endblock content %}

browse/templates/browse/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Workout benchmarks{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'browse/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'browse/css/fitjeb.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block navbar %}
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'browse:index' %}">Fit-j</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'browse:index' %}">Home</a></li>
            <li><a href="{% url 'browse:about' %}">About</a></li>
            <li><a href="{% url 'browse:contact' %}">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    {% endblock %}
    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'browse/js/bootstrap.min.js' %}"></script>
    <!-- A few lines to press down the buttons in the navbar -->
    <script src="{% static 'browse/js/fitjeb.js' %}"></script>
  </body>
</html>

browse/templates/browse/contact.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Contact{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Contact</h1>
        <p class="lead">Leave me a note at <a href="mailto:laudevelopment@gmail.com">laudevelopment@gmail.com</a> for feedback!</p>
    </div> <!-- jumbotron -->
</div>
{% endblock content %}

browse/templates/browse/index.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Workout Benchmark Index{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>WOD Benchmarks</h1>
        <p class="lead">Results from people who completed the main site WOD</p>
    </div> <!-- jumbotron -->

    <div class="row marketing">
        {% for workout in workout_list %}
        <div class="col-md-6 sleeve">
            <div class="card theme-one">
            <h4><a href="/wods/{{ workout.id }}/">{{ workout.title }}</a></h4>
            <p>{{ workout.description|truncatewords:20 }}</p>    
            </div>
        </div>
        {% empty %}
        <div class="col-md-12">
            <div class="theme-two">
            <h4>The workouts are populating. Please come back later.</h4>
            </div>
        </div>
        {% endfor %}
    </div> <!-- index list -->

    <div class="text-center">
    {% if is_paginated %}
        <ul class="pagination">
            {% if workout.has_previous %}
                <li><a href="?page={{ workout.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if workout.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if workout.has_next %}
                <li><a href="?page={{ workout.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
    </div> <!-- paginator -->
</div>
{% endblock content %}

browse/templates/browse/workoutdetail.html
{% extends "./base.html" %}
{% load static %}

{% block title %}{{ workout.title }}{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>{{ workout.title }}</h1>
    </div>

    <div class="row marketing">
        <div class="col-md-8">
            <div class="wod-benchmark">
                <table class="table table-hover theme-one">
                    <caption>Benchmark based on {{ workout.uom }}</caption> 
                    <thead> 
                        <tr> 
                            <th>Gender</th> 
                            <th>Rx'd</th>
                            <th>Min</th> 
                            <th>Avg</th> 
                            <th>Max</th>
                        </tr> 
                    </thead> 
                    <tbody>
                        {% for gender in benchmark_list %}
                        <tr>
                            <th scope="row">{{ gender.gender }}</th> 
                            <td>{{ gender.rx }}</td>
                            <td>{{ gender.min_score }}</td> 
                            <td>{{ gender.avg_score }}</td> 
                            <td>{{ gender.max_score }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4">
            <div class="wod-description theme-one">
                <p class="">{{ workout.description|linebreaks }}</p>
                <a href="{{ workout.link }}">Original post</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}